---
# tasks file for roles/database

- name: Run DB
  docker_container:
    name: database
    image: ttchpln/tp-devops-database:latest
    state: started
    networks: 
      - name: app-network
  vars:
    ansible_python_interpreter: /usr/bin/python3