version: '3.7'

services:
    backend:
        build: ./simple-api
        container_name: backend
        ports: 
            - "8081:8081"
        networks:
            - app-network
        depends_on:
            - database

    database:
        build: ./database
        container_name: database
        networks:
            - app-network

    httpd:
        build: ./http-server
        container_name: httpd
        networks:
            - app-network
        depends_on:
            - backend
    
    front:
        build: ./devops-front
        container_name: front
        networks: 
            - app-network
        depends_on:
            - httpd

networks:
    app-network: