version: '3.7'

services:
    backend:
        build: ./simple-api
        container_name: backend
        networks:
            - mynetwork
        depends_on:
            - database

    database:
        build: ./database
        container_name: database
        networks:
            - mynetwork

    httpd:
        build: ./http-server
        container_name: httpd
        ports:
            - "1212:80"
        networks:
            - mynetwork
        depends_on:
            - backend
    
    front:
        build: ./devops-front
        container-name: front
        networks: 
            - mynetwork
        depends-on:
            - httpd

networks:
    mynetwork: