---
# tasks file for roles/proxy

- name: Run HTTPD
  docker_container:
    name: httpd
    image: ttchpln/tp-devops-http-server:latest
    state: started
    networks: 
      - name: app-network
    ports: "80:80"
  vars:
    ansible_python_interpreter: /usr/bin/python3